# Generated by Django 3.2.19 on 2025-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='pH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='tds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='thermo',
            field=models.FloatField(default=0),
        ),
    ]
