# Generated by Django 3.2.19 on 2025-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0002_auto_20250407_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='waterLevel',
            field=models.CharField(max_length=10),
        ),
    ]
